export const siteConfig = {
  personal: {
    name: 'Haniya Haider',
    title: 'Professional Aesthetician',
    experience: '4+ years',
    phone: '+93221401833',
    whatsapp: '+93221401833',
    email: 'haniya.aesthetics@example.com',
    location: 'Available for Clinic Collaborations',
    image: '/haniya.jpeg',
    tagline: 'Advanced Aesthetic & Anti-Aging Treatments',
    description: 'Delivering safe, results-driven aesthetic procedures with 4+ years of hands-on experience. Available for clinic collaborations and on-call services.',
  },
  social: {
    instagram: 'https://instagram.com',
    facebook: 'https://facebook.com',
    linkedin: 'https://linkedin.com',
  },
  business: {
    name: 'Haniya Haider - Professional Aesthetician',
    type: 'Aesthetic Medicine',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'MedicalBusiness',
      name: 'Haniya Haider - Professional Aesthetician',
      image: '/haniya.jpeg',
      description: 'Professional aesthetician specializing in advanced aesthetic and anti-aging treatments with 4+ years of experience.',
      priceRange: '$$',
      telephone: '+93221401833',
    },
  },
  colors: {
    primary: {
      50: '#F4F0FB',
      100: '#E6DCF6',
      200: '#D0B9EE',
      300: '#B996E5',
      400: '#9E6FD9',
      500: '#7C4CCB',
      600: '#5A31AE',
      700: '#3A1B75',
      800: '#2E155E',
      900: '#1F0E3F',
    },
    secondary: {
      50: '#FBF8FD',
      100: '#F3ECF9',
      200: '#E6DCF6',
      300: '#D7C6EF',
      400: '#C6A7E2',
      500: '#B28BD6',
      600: '#9A6BC6',
      700: '#7C4FA8',
      800: '#5E3A7D',
      900: '#3F2654',
    },
    accent: '#D6B4E8',
    background: '#FFFCFF',
    text: {
      primary: '#1A1A1A',
      secondary: '#4A4A4A',
      light: '#6B7280',
      inverted: '#FFFFFF',
    },
  },
  seo: {
    titleTemplate: '%s | Haniya Haider - Professional Aesthetician',
    defaultTitle: 'Haniya Haider - Professional Aesthetician | Advanced Aesthetic Treatments',
    defaultDescription: 'Professional aesthetician with 4+ years of experience in advanced aesthetic and anti-aging treatments. Specializing in Botox, fillers, laser treatments, PRP therapy, and more.',
    siteUrl: 'https://haniyahaider.com',
    keywords: 'aesthetician, botox, dermal fillers, laser treatment, PRP therapy, anti-aging, aesthetic treatments, professional aesthetician',
  },
};

export type SiteConfig = typeof siteConfig;
