export const siteConfig = {
  personal: {
    name: 'Haniya Haider',
    title: 'Professional Aesthetician',
    experience: '4+ years',
    phone: '+93221401833',
    whatsapp: '+93221401833',
    email: 'haniya.aesthetics@example.com',
    location: 'Available for Clinic Collaborations',
    image: '/haniya.jpeg',
    tagline: 'Advanced Aesthetic & Anti-Aging Treatments',
    description: 'Delivering safe, results-driven aesthetic procedures with 4+ years of hands-on experience. Available for clinic collaborations and on-call services.',
  },
  social: {
    instagram: 'https://instagram.com',
    facebook: 'https://facebook.com',
    linkedin: 'https://linkedin.com',
  },
  business: {
    name: 'Haniya Haider - Professional Aesthetician',
    type: 'Aesthetic Medicine',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'MedicalBusiness',
      name: 'Haniya Haider - Professional Aesthetician',
      image: '/haniya.jpeg',
      description: 'Professional aesthetician specializing in advanced aesthetic and anti-aging treatments with 4+ years of experience.',
      priceRange: '$$',
      telephone: '+93221401833',
    },
  },
  colors: {
    primary: {
      50: '#fdf2f8',
      100: '#fce7f3',
      200: '#fbcfe8',
      300: '#f9a8d4',
      400: '#f472b6',
      500: '#ec4899',
      600: '#db2777',
      700: '#be185d',
      800: '#9d174d',
      900: '#831843',
    },
    rose: {
      50: '#fff1f2',
      100: '#ffe4e6',
      200: '#fecdd3',
      300: '#fda4af',
      400: '#fb7185',
      500: '#f43f5e',
      600: '#e11d48',
      700: '#be123c',
      800: '#9f1239',
      900: '#881337',
    },
    accent: '#d4af37',
    background: '#fffbfb',
    text: {
      primary: '#1a1a1a',
      secondary: '#4a4a4a',
      light: '#6b7280',
    },
  },
  seo: {
    titleTemplate: '%s | Haniya Haider - Professional Aesthetician',
    defaultTitle: 'Haniya Haider - Professional Aesthetician | Advanced Aesthetic Treatments',
    defaultDescription: 'Professional aesthetician with 4+ years of experience in advanced aesthetic and anti-aging treatments. Specializing in Botox, fillers, laser treatments, PRP therapy, and more.',
    siteUrl: 'https://haniyahaider.com',
    keywords: 'aesthetician, botox, dermal fillers, laser treatment, PRP therapy, anti-aging, aesthetic treatments, professional aesthetician',
  },
};

export type SiteConfig = typeof siteConfig;
